# Generated by Django 5.0.7 on 2025-10-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdultCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('instructor', models.CharField(max_length=120)),
                ('schedule', models.CharField(max_length=200)),
                ('tuition', models.DecimalField(decimal_places=2, max_digits=8)),
                ('seats', models.IntegerField(default=15)),
            ],
        ),
    ]
