# Generated by Django 5.0.7 on 2025-10-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_type', models.CharField(choices=[('TARDY', 'Tardy'), ('ABSENT', 'Absent'), ('BEHAVIOR', 'Behavior'), ('OTHER', 'Other')], max_length=16)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_incidents', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
