# Generated by Django 5.0.7 on 2025-10-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('credits', models.DecimalField(decimal_places=1, default=0.5, max_digits=4)),
                ('grade_min', models.PositiveIntegerField(default=6)),
                ('grade_max', models.PositiveIntegerField(default=12)),
                ('dual_enrollment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(default='FY', max_length=20)),
                ('teacher', models.CharField(blank=True, max_length=120, null=True)),
                ('room', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity', models.PositiveIntegerField(default=28)),
                ('schedule_pattern', models.CharField(default='standard', max_length=20)),
                ('m', models.BooleanField(default=True)),
                ('t', models.BooleanField(default=True)),
                ('w', models.BooleanField(default=True)),
                ('th', models.BooleanField(default=True)),
                ('f', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=120)),
                ('status', models.CharField(default='enrolled', max_length=20)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='scheduling.section')),
            ],
            options={
                'unique_together': {('section', 'student')},
            },
        ),
    ]
