name: Weekly Security Audit

on:
 schedule:
 - cron: '03 * *1' # weekly, Monday03:00 UTC
 workflow_dispatch:

jobs:
 audit:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v3
 - name: Set up Python
 uses: actions/setup-python@v4
 with:
 python-version: '3.10'
 - name: Install dependencies
 run: |
 python -m venv .venv
 . .venv/bin/activate
 python -m pip install --upgrade pip
 pip install -r requirements.txt
 - name: Run pip-audit
 run: |
 . .venv/bin/activate
 python -m pip install pip-audit
 pip-audit --format=json --output-file pip_audit.json || true
 - name: Upload results
 uses: actions/upload-artifact@v4
 with:
 name: pip_audit_report
 path: pip_audit.json
