# Generated by Django 5.0.7 on 2025-10-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=120)),
                ('value', models.FloatField(default=0)),
            ],
        ),
    ]
