---
name: API CI

on:
 push:
 branches:
 - main
 pull_request:
 branches:
 - main

jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout
 uses: actions/checkout@v4

 - name: Set up Python
 uses: actions/setup-python@v4
 with:
 python-version: '3.12'

 - name: Install dependencies
 run: |
 python -m pip install --upgrade pip
 python -m pip install -r apps/api/requirements-dev.txt

 - name: Run tests
 run: |
 python -m pip install pytest
 pytest -q

 - name: Build Docker image
 uses: docker/build-push-action@v4
 with:
 context: ./apps/api
 push: false
 tags: crown360/api:local tags: crown360/api:local