---
name: API CI

on:
 push:
 branches:
 - main
 pull_request:
 branches:
 - main

permissions:
 contents: read
 packages: write
 id-token: write

jobs:
 lint-test-build-and-push:
 name: Lint · Test · Build · Push
 runs-on: ubuntu-latest
 steps:
 - name: Checkout
 uses: actions/checkout@v4

 - name: Set up Python
 uses: actions/setup-python@v4
 with:
 python-version: '3.12'

 - name: Install dev dependencies
 run: |
 python -m pip install --upgrade pip
 if [ -f apps/api/requirements-dev.txt ]; then python -m pip install -r apps/api/requirements-dev.txt; fi

 - name: Run linters
 run: |
 if command -v ruff >/dev/null2>&1; then python -m ruff check apps/api || true; fi

 - name: Run tests
 run: |
 if [ -f apps/api/manage.py ]; then python -m pytest apps/api -q || true; fi

 - name: Set up Docker Buildx
 uses: docker/setup-buildx-action@v3

 - name: Login to GHCR
 uses: docker/login-action@v2
 with:
 registry: ghcr.io
 username: ${{ github.actor }}
 password: ${{ secrets.GITHUB_TOKEN }}

 - name: Build and push Docker image to GHCR
 uses: docker/build-push-action@v4
 with:
 context: ./apps/api
 file: ./apps/api/Dockerfile
 push: true
 platforms: linux/amd64,linux/arm64
 tags: |
 ghcr.io/${{ github.repository_owner }}/crown360-api:latest
 ghcr.io/${{ github.repository_owner }}/crown360-api:${{ github.sha }}