---
name: Deploy API to Azure

on:
 workflow_dispatch:

jobs:
 deploy:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout
 uses: actions/checkout@v4

 - name: Run placeholder
 run: echo "Deploy - placeholder"
