---
name: Deploy API to Azure

on:
 workflow_dispatch:

permissions:
 id-token: write
 contents: read

jobs:
 deploy:
 name: Deploy to Azure Web App (Container)
 runs-on: ubuntu-latest
 steps:
 - name: Checkout
 uses: actions/checkout@v4

 - name: Login to Azure using OIDC
 uses: azure/login@v2
 with:
 client-id: ${{ secrets.AZURE_CLIENT_ID }}
 tenant-id: ${{ secrets.AZURE_TENANT_ID }}
 subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

 - name: Pull image from GHCR
 run: |
 echo "Pulling image"
 docker pull ghcr.io/${{ github.repository_owner }}/crown360-api:latest || true

 - name: Deploy to Web App for Containers
 uses: azure/webapps-deploy@v2
 with:
 app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
 images: ghcr.io/${{ github.repository_owner }}/crown360-api:latest
