---
name: Deploy API

on: [workflow_dispatch]

jobs:
 deploy:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v4
 - name: Login to Azure
 uses: azure/login@v2
 with:
 creds: ${{ secrets.AZURE_CREDENTIALS }}
 - name: Deploy placeholder
 run: echo "deploy placeholder"
