---
name: Deploy API

on:
 workflow_dispatch:

permissions:
 id-token: write
 contents: read

jobs:
 deploy:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout
 uses: actions/checkout@v4

 - name: Login to Azure
 uses: azure/login@v2
 with:
 creds: ${{ secrets.AZURE_CREDENTIALS }}

 - name: Deploy to App Service
 uses: azure/webapps-deploy@v2
 with:
 app-name: crown2-api
 slot-name: production
 package: ./apps/api
