---
name: Web CI

on:
 push:
 branches:
 - main
 pull_request:
 branches:
 - main

jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout
 uses: actions/checkout@v4

 - name: Run placeholder
 run: echo "Web CI - placeholder"
