---
name: Web CI

on: [push]

jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v4
 - name: Set up Node
 uses: actions/setup-node@v4
 with:
 node-version: '20'
 - name: Install pnpm
 run: npm i -g pnpm
 - name: Install deps
 run: pnpm i --prefix apps/web
 - name: Build
 run: pnpm --prefix apps/web build
 - name: Upload artifact
 uses: actions/upload-artifact@v4
 with:
 name: web-build
 path: apps/web/dist
