---
name: Web CI

on:
 push:
 branches:
 - main
 pull_request:
 branches:
 - main

jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v4
 - name: Echo
 run: echo "Web CI placeholder"
