# Generated by Django 5.0.7 on 2025-10-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=120)),
                ('tutor', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
