# Generated by Django 5.0.7 on 2025-10-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('curriculum_source', models.CharField(choices=[('BJU', 'BJU Press'), ('Abeka', 'Abeka'), ('PAC', 'Positive Action for Christ'), ('PD', 'Purposeful Design')], max_length=80)),
                ('grade_level', models.IntegerField()),
                ('credits', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('topic', models.CharField(max_length=200)),
                ('objectives', models.TextField()),
                ('scripture_integration', models.CharField(blank=True, max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
        ),
    ]
