# Generated by Django 5.0.7 on 2025-10-19 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=9)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('awarded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEW', 'In Review'), ('AWARDED', 'Awarded'), ('DENIED', 'Denied')], default='SUBMITTED', max_length=16)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_applications', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
