name: Secret Scan

on:
 pull_request:
 push:
 branches: [ main ]

jobs:
 secret-scan:
 name: Scan repository for common secret patterns
 runs-on: ubuntu-latest
 steps:
 - name: Checkout
 uses: actions/checkout@v4
 - name: Run secret pattern scanner
 run: |
 set -euo pipefail
 echo "Scanning repository for common secret patterns..."
 # Define regex for common secrets
 PATTERNS="github_pat_|ghp_|GITHUB_TOKEN|AWS_ACCESS_KEY_ID|AKIA[0-9A-Z]{16}|-----BEGIN PRIVATE KEY-----"
 # Search tracked files (exclude node_modules and dist)
 if git grep -n --full-name -I -E "$PATTERNS" -- ':!node_modules' ':!dist' ':!.git' ; then
 echo "ERROR: Potential secret pattern found in repository. Aborting." >&2
 git grep -n --full-name -I -E "$PATTERNS" -- ':!node_modules' ':!dist' ':!.git' >&2
 exit1
 else
 echo "No obvious secret patterns found."
 fi
