---
name: Web CI

on:
 pull_request:
 branches: [ main ]
 push:
 branches: [ main ]

jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v4
 - name: Setup Node
 uses: actions/setup-node@v4
 with:
 node-version: '18'
 cache: 'pnpm'
 - name: Install pnpm
 run: corepack enable && corepack prepare pnpm@latest --activate
 - name: Cache pnpm store
 uses: actions/cache@v4
 with:
 path: ~/.pnpm-store
 key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
 - name: Cache node modules
 uses: actions/cache@v4
 with:
 path: apps/web/node_modules
 key: ${{ runner.os }}-node-modules-${{ hashFiles('apps/web/pnpm-lock.yaml') }}
 - name: Install dependencies
 working-directory: apps/web
 run: pnpm install --frozen-lockfile
 - name: Typecheck
 working-directory: apps/web
 run: pnpm exec tsc --noEmit
 - name: Build
 working-directory: apps/web
 run: pnpm run build
 - name: Lint
 working-directory: apps/web
 run: pnpm run lint
 - name: Format check
 working-directory: apps/web
 run: pnpm run format -- --check
